import difflib
from config.settings import FUZZY_THRESHOLD

# All aliases -> canonical lowercase city name.
CITY_ALIASES: dict[str, str] = {
    "bangalore":         "bengaluru",
    "bengaluru":         "bengaluru",
    "bengalore":         "bengaluru",
    "blr":               "bengaluru",
    "mumbai":            "mumbai",
    "bombay":            "mumbai",
    "mum":               "mumbai",
    "delhi":             "delhi",
    "new delhi":         "delhi",
    "ncr":               "delhi",
    "gurugram":          "gurugram",
    "gurgaon":           "gurugram",
    "hyderabad":         "hyderabad",
    "hyd":               "hyderabad",
    "secunderabad":      "hyderabad",
    "chennai":           "chennai",
    "madras":            "chennai",
    "kolkata":           "kolkata",
    "calcutta":          "kolkata",
    "mysuru":            "mysuru",
    "mysore":            "mysuru",
    "mysor":             "mysuru",
    "mysur":             "mysuru",
    "kochi":             "kochi",
    "cochin":            "kochi",
    "ernakulam":         "kochi",
    "thiruvananthapuram": "thiruvananthapuram",
    "trivandrum":        "thiruvananthapuram",
    "tvm":               "thiruvananthapuram",
    "visakhapatnam":     "visakhapatnam",
    "vizag":             "visakhapatnam",
    "vishakhapatnam":    "visakhapatnam",
    "bhubaneswar":       "bhubaneswar",
    "bbsr":              "bhubaneswar",
    "pune":              "pune",
    "poona":             "pune",
    "noida":             "noida",
    "ahmedabad":         "ahmedabad",
    "amdavad":           "ahmedabad",
    "jaipur":            "jaipur",
    "pink city":         "jaipur",
    "lucknow":           "lucknow",
    "chandigarh":        "chandigarh",
    "indore":            "indore",
    "coimbatore":        "coimbatore",
    "cbe":               "coimbatore",
    "nagpur":            "nagpur",
    "bhopal":            "bhopal",
    "surat":             "surat",
    "patna":             "patna",
    "vadodara":          "vadodara",
    "baroda":            "vadodara",
    "madurai":           "madurai",
    "tiruchirappalli":   "tiruchirappalli",
    "trichy":            "tiruchirappalli",
    "salem":             "salem",
    "tirunelveli":       "tirunelveli",
    "erode":             "erode",
    "vijayawada":        "vijayawada",
    "guntur":            "guntur",
    "tirupati":          "tirupati",
    "warangal":          "warangal",
    "mangaluru":         "mangaluru",
    "mangalore":         "mangaluru",
    "hubli":             "hubballi",
    "hubballi":          "hubballi",
    "hubli-dharwad":     "hubballi",
    "belagavi":          "belagavi",
    "belgaum":           "belagavi",
    "ranchi":            "ranchi",
    "jamshedpur":        "jamshedpur",
    "guwahati":          "guwahati",
    "gauhati":           "guwahati",
    "dehradun":          "dehradun",
    "ghaziabad":         "ghaziabad",
    "faridabad":         "faridabad",
    "meerut":            "meerut",
    "agra":              "agra",
    "varanasi":          "varanasi",
    "banaras":           "varanasi",
    "kashi":             "varanasi",
    "jodhpur":           "jodhpur",
    "udaipur":           "udaipur",
    "amritsar":          "amritsar",
    "ludhiana":          "ludhiana",
    "raipur":            "raipur",
    "nashik":            "nashik",
    "aurangabad":        "aurangabad",
    "puducherry":        "puducherry",
    "pondicherry":       "puducherry",
    "kolhapur":          "kolhapur",
    "solapur":           "solapur",
    "kozhikode":         "kozhikode",
    "calicut":           "kozhikode",
    "thrissur":          "thrissur",
    "kollam":            "kollam",
    "kannur":            "kannur",
    "gwalior":           "gwalior",
    "jabalpur":          "jabalpur",
    "ujjain":            "ujjain",
    "rajkot":            "rajkot",
    "gandhinagar":       "gandhinagar",
    "panaji":            "panaji",
    "panjim":            "panaji",
    "srinagar":          "srinagar",
    "jammu":             "jammu",
    "shimla":            "shimla",
    "remote":            "remote",
    "wfh":               "remote",
    "work from home":    "remote",
    "anywhere":          "remote",
    "india":             "india",
    "pan india":         "india",
    "all india":         "india",
    "nationwide":        "india",
}

# City -> state (lowercase), used for state-level fallback matching
CITY_STATE_MAP: dict[str, str] = {
    "bengaluru":      "karnataka",
    "mysuru":         "karnataka",
    "mangaluru":      "karnataka",
    "hubballi":       "karnataka",
    "belagavi":       "karnataka",
    "davangere":      "karnataka",
    "ballari":        "karnataka",
    "mumbai":         "maharashtra",
    "pune":           "maharashtra",
    "nagpur":         "maharashtra",
    "nashik":         "maharashtra",
    "aurangabad":     "maharashtra",
    "solapur":         "maharashtra",
    "kolhapur":       "maharashtra",
    "delhi":          "delhi",
    "noida":          "uttar pradesh",
    "ghaziabad":      "uttar pradesh",
    "gurugram":       "haryana",
    "faridabad":      "haryana",
    "hyderabad":      "telangana",
    "warangal":       "telangana",
    "nizamabad":      "telangana",
    "karimnagar":     "telangana",
    "chennai":        "tamil nadu",
    "coimbatore":     "tamil nadu",
    "madurai":        "tamil nadu",
    "tiruchirappalli":"tamil nadu",
    "salem":          "tamil nadu",
    "tirunelveli":    "tamil nadu",
    "erode":          "tamil nadu",
    "kochi":          "kerala",
    "thiruvananthapuram": "kerala",
    "kozhikode":      "kerala",
    "thrissur":       "kerala",
    "kollam":         "kerala",
    "kannur":         "kerala",
    "ahmedabad":      "gujarat",
    "surat":          "gujarat",
    "vadodara":       "gujarat",
    "rajkot":         "gujarat",
    "gandhinagar":    "gujarat",
    "jaipur":         "rajasthan",
    "jodhpur":        "rajasthan",
    "udaipur":        "rajasthan",
    "kota":           "rajasthan",
    "ajmer":          "rajasthan",
    "visakhapatnam":  "andhra pradesh",
    "vijayawada":     "andhra pradesh",
    "guntur":         "andhra pradesh",
    "tirupati":       "andhra pradesh",
    "kakinada":       "andhra pradesh",
    "kolkata":        "west bengal",
    "amritsar":       "punjab",
    "ludhiana":       "punjab",
    "jalandhar":      "punjab",
    "chandigarh":     "chandigarh",
    "indore":            "madhya pradesh",
    "bhopal":            "madhya pradesh",
    "gwalior":           "madhya pradesh",
    "jabalpur":          "madhya pradesh",
    "ujjain":            "madhya pradesh",
    "lucknow":        "uttar pradesh",
    "agra":           "uttar pradesh",
    "varanasi":       "uttar pradesh",
    "meerut":         "uttar pradesh",
    "bhubaneswar":    "odisha",
    "patna":          "bihar",
    "ranchi":         "jharkhand",
    "jamshedpur":     "jharkhand",
    "dhanbad":        "jharkhand",
    "guwahati":       "assam",
    "dehradun":       "uttarakhand",
    "haridwar":       "uttarakhand",
    "raipur":         "chhattisgarh",
    "bhilai":         "chhattisgarh",
    "panaji":         "goa",
    "margao":         "goa",
    "gurugram":       "haryana",
    "faridabad":      "haryana",
}

# Nearby city chains: when city has 0 results, try these in order
NEARBY_CITIES: dict[str, list[str]] = {
    "mysuru":            ["bengaluru", "karnataka", "remote", "india"],
    "mangaluru":         ["bengaluru", "karnataka", "remote", "india"],
    "hubballi":          ["bengaluru", "karnataka", "remote", "india"],
    "belagavi":          ["pune", "bengaluru", "karnataka", "remote", "india"],
    "noida":             ["delhi", "gurugram", "uttar pradesh", "remote", "india"],
    "gurugram":          ["delhi", "noida", "haryana", "remote", "india"],
    "ghaziabad":         ["delhi", "noida", "uttar pradesh", "remote", "india"],
    "faridabad":         ["delhi", "gurugram", "haryana", "remote", "india"],
    "warangal":          ["hyderabad", "telangana", "remote", "india"],
    "visakhapatnam":     ["hyderabad", "andhra pradesh", "remote", "india"],
    "vijayawada":        ["hyderabad", "andhra pradesh", "remote", "india"],
    "coimbatore":        ["chennai", "bengaluru", "tamil nadu", "remote", "india"],
    "madurai":           ["chennai", "tamil nadu", "remote", "india"],
    "tiruchirappalli":   ["chennai", "coimbatore", "tamil nadu", "remote", "india"],
    "kochi":             ["thiruvananthapuram", "bengaluru", "kerala", "remote", "india"],
    "thiruvananthapuram":["kochi", "kerala", "remote", "india"],
    "kozhikode":         ["kochi", "kerala", "remote", "india"],
    "nagpur":            ["pune", "mumbai", "maharashtra", "remote", "india"],
    "nashik":            ["pune", "mumbai", "maharashtra", "remote", "india"],
    "aurangabad":        ["pune", "mumbai", "maharashtra", "remote", "india"],
    "surat":             ["ahmedabad", "mumbai", "gujarat", "remote", "india"],
    "vadodara":          ["ahmedabad", "gujarat", "remote", "india"],
    "rajkot":            ["ahmedabad", "gujarat", "remote", "india"],
    "gandhinagar":       ["ahmedabad", "gujarat", "remote", "india"],
    "jaipur":            ["delhi", "noida", "rajasthan", "remote", "india"],
    "jodhpur":           ["jaipur", "rajasthan", "remote", "india"],
    "udaipur":           ["jaipur", "rajasthan", "remote", "india"],
    "chandigarh":        ["delhi", "noida", "punjab", "remote", "india"],
    "amritsar":          ["chandigarh", "delhi", "punjab", "remote", "india"],
    "ludhiana":          ["chandigarh", "delhi", "punjab", "remote", "india"],
    "lucknow":           ["noida", "delhi", "uttar pradesh", "remote", "india"],
    "agra":              ["noida", "delhi", "uttar pradesh", "remote", "india"],
    "varanasi":          ["patna", "lucknow", "uttar pradesh", "remote", "india"],
    "indore":            ["bhopal", "pune", "madhya pradesh", "remote", "india"],
    "bhopal":            ["indore", "nagpur", "madhya pradesh", "remote", "india"],
    "gwalior":           ["noida", "bhopal", "madhya pradesh", "remote", "india"],
    "raipur":            ["nagpur", "bhopal", "chhattisgarh", "remote", "india"],
    "patna":             ["kolkata", "bihar", "remote", "india"],
    "ranchi":            ["kolkata", "jharkhand", "remote", "india"],
    "jamshedpur":        ["kolkata", "jharkhand", "remote", "india"],
    "bhubaneswar":       ["kolkata", "odisha", "remote", "india"],
    "guwahati":          ["kolkata", "assam", "remote", "india"],
    "dehradun":          ["noida", "delhi", "uttarakhand", "remote", "india"],
    "panaji":            ["mumbai", "pune", "goa", "remote", "india"],
    "srinagar":          ["delhi", "jammu", "remote", "india"],
    "jammu":             ["delhi", "chandigarh", "remote", "india"],
}

# All known Indian locations (cities + states) — used for "is this an Indian query?"
_ALL_INDIAN_LOCATIONS: set[str] = set(CITY_ALIASES.keys()) | set(CITY_STATE_MAP.keys()) | {
    "india", "remote", "karnataka", "maharashtra", "delhi", "uttar pradesh",
    "haryana", "telangana", "andhra pradesh", "tamil nadu", "kerala", "gujarat",
    "rajasthan", "west bengal", "punjab", "chandigarh", "madhya pradesh",
    "odisha", "bihar", "jharkhand", "assam", "uttarakhand", "chhattisgarh",
    "goa", "himachal pradesh", "jammu and kashmir", "north east", "north india",
    "south india",
}

# Pre-computed map of canonical city -> list of its aliases (optimization)
CANONICAL_TO_ALIASES: dict[str, list[str]] = {}
for alias, canon in CITY_ALIASES.items():
    canon_lower = canon.lower()
    if canon_lower not in CANONICAL_TO_ALIASES:
        CANONICAL_TO_ALIASES[canon_lower] = []
    CANONICAL_TO_ALIASES[canon_lower].append(alias)

def normalize_city(raw: str) -> str:
    """Return lowercase canonical city name for a raw input string.

    Applies exact alias lookup first, then falls back to fuzzy matching
    against the alias keys at >= FUZZY_THRESHOLD similarity.
    """
    if not raw:
        return ""
    lower = raw.strip().lower()

    # Direct alias hit
    if lower in CITY_ALIASES:
        return CITY_ALIASES[lower]

    # Fuzzy match against alias keys (handles typos like "mysor", "mysur")
    matches = difflib.get_close_matches(lower, CITY_ALIASES.keys(), n=1, cutoff=FUZZY_THRESHOLD)
    if matches:
        return CITY_ALIASES[matches[0]]

    # If no alias hit, return as-is (lowercase)
    return lower

def _is_indian_query(city_canonical: str) -> bool:
    """Return True if the normalised city is a known Indian location."""
    return (
        city_canonical in _ALL_INDIAN_LOCATIONS
        or city_canonical in CITY_STATE_MAP
    )
